### ISSUE TITLE
The code is Docker Hub specific. Should be made more generic to allow any private registry

### ISSUE THREAD

**Issue by jerbia** [pmalek/docker_download#1]
The code has hard-coded Docker Hub URLs, which means it will not work with any container registry. These hard-coded URLs should be removed and taken from the image prefix.

**Comment by pmalek** [comment]
> These hard-coded URLs should be removed and taken from the image prefix.

Can you elaborate a bit more on this? When you want to e.g. pull an image you specify the repo and image name like so: `mysql/mysql-server`. What is "image prefix" for you?

Do you  have in mind that you pass to this app a full URL like:

    registry.SOMEWHERE.com/USER/IMAGENAME:REF_VERSION

or pass registry URL separately with another parameter?

**Comment by jerbia** [comment]
A private container registry will have the following syntax:
<registry DNS>/user/repository:<tag>

There are also cases where a private registry will support nested repositories, e.g.
<registry DNS>/namespace/user/repository:<tag>
